### ISSUE TITLE
get_detector_model not defined

### ISSUE THREAD

**Issue by Alex-fishred** [alaamaalouf/FollowAnything#1]
thanks for the great work!!
I am executing "python annotate_features.py --desired_height 240 --desired_width 320 --queries_dir /home/islab/FollowAnything/FollowAnything --path_to_images /home/islab/FollowAnything/FollowAnything/example_img"
but in annotate_features.py appear
NameError: name 'get_detector_model' is not defined
how to solve?

**Comment by alaamaalouf** [comment]
thanks for your interest in our paper. 

"get_detector_model" should be changed to  "get_dino_pixel_wise_features_model"

Fix was pushed :+1:

**Comment by Alex-fishred** [comment]
thank you 
problem solved!
